version: "3.9"
networks: 
  t2_proxy: 
    driver: bridge
    name: t2_proxy
services: 
  organizr:
    image: organizr/organizr
    container_name: organizr
    environment:
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
    networks: 
      - t2_proxy
    volumes:
      - "${DOCKERDIR}/mediaserver/organizer:/config"
    ports:
      - ${ORGANIZER_PORT}:80
    restart: unless-stopped
  readarr:
    image: linuxserver/readarr:amd64-nightly-version-0.1.0.971
    container_name: readarr
    environment:
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
    networks: 
      - t2_proxy
    volumes:
      - ${DOCKERDIR}/mediaserver/readarr:/config
      - ${USERDIR}/data/media/books:/books #optional
#      - /path/to/downloadclient-downloads:/downloads #optional
    ports:
      - ${READARR_PORT}:8787
    restart: unless-stopped    
  deluge: 
    container_name: deluge
    depends_on: 
      - pia-vpn
    environment: 
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
      - DELUGE_LOGLEVEL=error
    image: adamfisher90/docker-deluge-1.3.11
    network_mode: "service:pia-vpn"
    restart: unless-stopped
    volumes: 
      - "${DOCKERDIR}/mediaserver/deluge:/config"
      - "${USERDIR}/data/torrents:/downloads"
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
    networks: 
      - t2_proxy  
    volumes:
       - "${DOCKERDIR}/mediaserver/prowlarr:/config"
    ports:
      - "${PROWLARR_PORT}:9696"
    restart: unless-stopped
  pia-vpn: 
    cap_add: 
      - net_admin
    container_name: pia-vpn
    dns: 
      - "209.222.18.222"
      - "209.222.18.218"
    environment: 
      PASSWORD: "${PIA_PASSWORD}"
      REGION: "US East"
      USERNAME: "${PIA_USERNAME}"
    image: "itsdaspecialk/pia-openvpn:centos7"
#    network_mode: host
    networks:
     - t2_proxy
    ports: 
      - "${PIA_PORT}:9091"
      - "${DELUGE_PORT1}:8112"
      - "${DELUGE_PORT2}:6881"
    restart: always
# plexms: 
#   container_name: plexms
#   devices: 
#     - "/dev/dri:/dev/dri"
#   environment: 
#     ADVERTISE_IP: "http://$SERVER_IP:32400/"
#     HOSTNAME: MultiPlex
#     PLEX_CLAIM_FILE: $PLEX_CLAIM
#     PLEX_GID: $PGID
#     PLEX_UID: $PUID
#     TZ: $TZ
#   image: "plexinc/pms-docker:latest"
#   #network_mode: host
#   networks: 
#     - t2_proxy
#   restart: unless-stopped
#   security_opt: 
#     - "no-new-privileges:true"
#   ports:
#    - "32400:32400/tcp"
#    - "3005:3005/tcp"
#    - "8324:8324/tcp"
#    - "32469:32469/tcp"
#    - "1900:1900/udp"
#    - "32410:32410/udp"
#    - "32412:32412/udp"
#    - "32413:32413/udp"
#    - "32414:32414/udp"
#   volumes: 
#     - "$DOCKERDIR/mediaserver/plexms:/config"
#     - "${USERDIR}/data/media:/media"
#     - "/dev/shm:/transcode"
  plexms: 
    container_name: plexms
    devices: 
      - "/dev/dri:/dev/dri"
    environment: 
      ADVERTISE_IP: "http://$SERVER_IP:32400/"
      HOSTNAME: synPlex
      PLEX_CLAIM_FILE: $PLEX_CLAIM
      PLEX_GID: $PGID
      PLEX_UID: $PUID
      TZ: $TZ
    image: "plexinc/pms-docker:latest"
    network_mode: host
    restart: unless-stopped
    security_opt: 
      - "no-new-privileges:true"
    volumes: 
      - "$DOCKERDIR/mediaserver/plexms:/config"
      - "${USERDIR}/data/media:/media"
      - "/dev/shm:/transcode"
  radarr: 
    container_name: radarr
    environment: 
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
    image: "linuxserver/radarr:latest"
    networks: 
      - t2_proxy
    ports: 
      - "$RADARR_PORT:7878"
    restart: always
    security_opt: 
      - "no-new-privileges:true"
    volumes: 
      - "${DOCKERDIR}/mediaserver/radarr:/config"
      - "${USERDIR}/data:/data"
      - "/etc/localtime:/etc/localtime:ro"
      - "${DOCKERDIR}/mediaserver/shared:/shared"
  sabnzbd: 
    container_name: sabnzbd
    environment: 
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
    image: linuxserver/sabnzbd
    networks: 
      - t2_proxy
    ports: 
      - "$SABDNZD_PORT:8080"
    restart: always
    security_opt: 
      - "no-new-privileges:true"
    volumes: 
      - "${DOCKERDIR}/mediaserver/sabnzbd:/config"
      - "${USERDIR}/data/usenet:/data/usenet:rw"
      - "${DOCKERDIR}/mediaserver/shared:/shared"
  sonarr: 
    container_name: sonarr
    environment: 
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
    image: "linuxserver/sonarr:latest"
    networks: 
      - t2_proxy
    ports: 
      - "${SONARR_PORT}:8989"
    restart: always
    security_opt: 
      - "no-new-privileges:true"
    volumes: 
      - "${DOCKERDIR}/mediaserver/sonarr:/config"
      - "${USERDIR}/data:/data"
      - "/etc/localtime:/etc/localtime:ro"
      - "${DOCKERDIR}/mediaserver/shared:/shared"
  xteve: 
    container_name: xteve
    environment: 
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
    image: "bl0m1/xtevedocker:latest"
 #   image: "brycelarge/xteve-docker"
 #   network_mode: host
    networks: 
     - t2_proxy
    ports: 
      - "${XTEVE_PORT1}:34400"
      - "${XTEVE_PORT2}:1900"
    volumes: 
      - "${DOCKERDIR}/mediaserver/xteve:/home/xteve/.xteve"
