version: "3.9"
services: 
  deluge: 
    container_name: deluge
    depends_on: 
      - gluetun
    environment: 
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
      - "DELUGE_LOGLEVEL=error"
    image: lscr.io/linuxserver/deluge
    network_mode: "service:gluetun"
    restart: unless-stopped
    volumes: 
      - "${DOCKERDIR}/mediaserver/deluge:/config"
      - "${USERDIR}/data/torrents:/downloads"
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
    volumes:
       - "${DOCKERDIR}/mediaserver/prowlarr:/config"
    ports:
      - "${PROWLARR_PORT}:9696"
    restart: unless-stopped
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - ${GLUETON_PORT1}:8888/tcp # HTTP proxy
      - ${GLUETON_PORT2}:8388/tcp # Shadowsocks
      - ${GLUETON_PORT3}:8388/udp # Shadowsocks
      - "${DELUGE_PORT1}:8112"
      - "${DELUGE_PORT2}:6881"
      - "${XTEVE_PORT1}:34400"
      - "${XTEVE_PORT2}:1900"   
    volumes:
      - ${DOCKERDIR}/mediaserver:/gluetun
    environment:
      - VPNSP=private internet access
      - OPENVPN_USER=${PIA_USERNAME}
      - OPENVPN_PASSWORD=${PIA_PASSWORD}
      - REGION=US Streaming Optimized    
#  pia-vpn: 
#    cap_add: 
#      - net_admin
#    container_name: pia-vpn
#    dns: 
#      - "209.222.18.222"
#      - "209.222.18.218"
#    volumes:
#       - "${DOCKERDIR}/mediaserver/piavpn/normal:/normal"
#       - "${DOCKERDIR}/mediaserver/piavpn/strong:/strong"
#    environment: 
#      PASSWORD: "${PIA_PASSWORD}"
      #REGION: "US Atlanta"
#      USERNAME: "${PIA_USERNAME}"
#    image: "itsdaspecialk/pia-openvpn:centos7"
#    ports: 
#      - "${PIA_PORT}:9091"
#      - "${DELUGE_PORT1}:8112"
#      - "${DELUGE_PORT2}:6881"
      #- "${XTEVE_PORT1}:34400"
      #- "${XTEVE_PORT2}:1900"      
 #   restart: always
  plexms: 
    container_name: plexms
    devices: 
      - "/dev/dri:/dev/dri"
    environment: 
      ADVERTISE_IP: "http://$SERVER_IP:32400/"
      HOSTNAME: synPlex
      PLEX_CLAIM_FILE: $PLEX_CLAIM
      PLEX_GID: $PGID
      PLEX_UID: $PUID
      TZ: $TZ
    image: "plexinc/pms-docker:latest"
    network_mode: host
    restart: unless-stopped
    security_opt: 
      - "no-new-privileges:true"
    volumes: 
      - "$DOCKERDIR/mediaserver/plexms:/config"
      - "${USERDIR}/data/media:/media"
      - "/dev/shm:/transcode"
  radarr: 
    container_name: radarr
    environment: 
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
    image: "linuxserver/radarr:latest"
    ports: 
      - "$RADARR_PORT:7878"
    restart: always
    security_opt: 
      - "no-new-privileges:true"
    volumes: 
      - "${DOCKERDIR}/mediaserver/radarr:/config"
      - "${USERDIR}/data:/data"
      - "/etc/localtime:/etc/localtime:ro"
      - "${DOCKERDIR}/mediaserver/shared:/shared"
  sabnzbd: 
    container_name: sabnzbd
    environment: 
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
    image: linuxserver/sabnzbd
    ports: 
      - "$SABDNZD_PORT:8080"
    restart: always
    security_opt: 
      - "no-new-privileges:true"
    volumes: 
      - "${DOCKERDIR}/mediaserver/sabnzbd:/config"
      - "${USERDIR}/data/usenet:/data/usenet:rw"
      - "${DOCKERDIR}/mediaserver/shared:/shared"
  sonarr: 
    container_name: sonarr
    environment: 
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
    image: "linuxserver/sonarr:latest"
    ports: 
      - "${SONARR_PORT}:8989"
    restart: always
    security_opt: 
      - "no-new-privileges:true"
    volumes: 
      - "${DOCKERDIR}/mediaserver/sonarr:/config"
      - "${USERDIR}/data:/data"
      - "/etc/localtime:/etc/localtime:ro"
      - "${DOCKERDIR}/mediaserver/shared:/shared"
#  xteve: 
#    container_name: xteve
#    environment: 
#      - "PUID=${PUID}"
#      - "PGID=${PGID}"
#      - "TZ=${TZ}"
#    image: "bl0m1/xtevedocker:latest"
#    ports: 
#      - "${XTEVE_PORT1}:34400"
#      - "${XTEVE_PORT2}:1900"
#    volumes: 
#      - "${DOCKERDIR}/mediaserver/xteve:/home/xteve/.xteve"
  xteve: 
    container_name: xteve
    depends_on: 
      - gluetun
    network_mode: "service:gluetun"
    restart: unless-stopped
    environment: 
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
    image: "bl0m1/xtevedocker:latest"
    volumes: 
      - "${DOCKERDIR}/mediaserver/xteve:/home/xteve/.xteve"
