version: "3.9"
services: 
  ombi:
    image: lscr.io/linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - BASE_URL=/ombi #optional
    volumes:
      - ${DOCKERDIR}/mediaserver/ombi:/config
    ports:
      - ${OMBI_PORT}:3579
    restart: unless-stopped
  deluge: 
    container_name: deluge
    depends_on: 
      - gluetun
    environment: 
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
      - "DELUGE_LOGLEVEL=error"
    image: lscr.io/linuxserver/deluge
    network_mode: "service:gluetun"
    restart: unless-stopped
    volumes: 
      - "${DOCKERDIR}/mediaserver/deluge:/config"
      - "${USERDIR}/data/torrents:/downloads"
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
      - "JELLYFIN_PublishedServerUrl=192.168.0.5"
      #- "JELLYFIN_PublishedServerUrl=http://${SERVER_IP}:8096"
    volumes:
      - $DOCKERDIR/mediaserver/jellyfin:/config
      - ${USERDIR}/data/media/tv:/data/tvshows
      - ${USERDIR}/data/media/movies:/data/movies
    ports:
      - "${JELLYFIN_PORT1}:8096/tcp"
      - "${JELLYFIN_PORT2}:8920/tcp"
      - "${JELLYFIN_PORT3}:7359/udp" #optional
      - "${JELLYFIN_PORT4}:1900/udp" #optional
    restart: unless-stopped
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
    volumes:
       - "${DOCKERDIR}/mediaserver/prowlarr:/config"
    ports:
      - "${PROWLARR_PORT}:9696"
    restart: unless-stopped
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - ${GLUETON_PORT1}:8888/tcp # HTTP proxy
      - ${GLUETON_PORT2}:8388/tcp # Shadowsocks
      - ${GLUETON_PORT3}:8388/udp # Shadowsocks
      - "${DELUGE_PORT1}:8112"
      - "${DELUGE_PORT2}:6881"
      - "${XTEVE_PORT1}:34400"
      - "${XTEVE_PORT2}:1900"
      - "${FIREFOX_PORT}:3000"
      #- "${SONARR_PORT}:8989"
    volumes:
      - ${DOCKERDIR}/mediaserver:/gluetun
    environment:
      - VPNSP=private internet access
      - OPENVPN_USER=${PIA_USERNAME}
      - OPENVPN_PASSWORD=${PIA_PASSWORD}
      - REGION=US Streaming Optimized    
  plexms: 
    container_name: plex
    devices: 
      - "/dev/dri:/dev/dri"
    environment: 
      ADVERTISE_IP: "http://$SERVER_IP:32400/"
      HOSTNAME: synPlex
      PLEX_CLAIM_FILE: $PLEX_CLAIM
      PLEX_GID: $PGID
      PLEX_UID: $PUID
      TZ: $TZ
    image: "plexinc/pms-docker:latest"
    network_mode: host
    restart: unless-stopped
    security_opt: 
      - "no-new-privileges:true"
    volumes: 
      - "$DOCKERDIR/mediaserver/plexms:/config"
      - "${USERDIR}/data/media:/media"
      - "/dev/shm:/transcode"
  radarr: 
    container_name: radarr
    environment: 
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
    image: "linuxserver/radarr:latest"
    ports: 
      - "$RADARR_PORT:7878"
    restart: always
    security_opt: 
      - "no-new-privileges:true"
    volumes: 
      - "${DOCKERDIR}/mediaserver/radarr:/config"
      - "${USERDIR}/data:/data"
      - "/etc/localtime:/etc/localtime:ro"
      - "${DOCKERDIR}/mediaserver/shared:/shared"
  sabnzbd: 
    container_name: sabnzbd
    environment: 
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
    image: linuxserver/sabnzbd
    ports: 
      - "$SABDNZD_PORT:8080"
    restart: always
    security_opt: 
      - "no-new-privileges:true"
    volumes: 
      - "${DOCKERDIR}/mediaserver/sabnzbd:/config"
      - "${USERDIR}/data/usenet:/data/usenet:rw"
      - "${DOCKERDIR}/mediaserver/shared:/shared"
  sonarr: 
    container_name: sonarr
    environment: 
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
    image: "linuxserver/sonarr:latest"
    #depends_on: 
    #  - gluetun
    #network_mode: "service:gluetun"
    ports: 
      - "${SONARR_PORT}:8989"
    restart: always
    security_opt: 
      - "no-new-privileges:true"
    volumes: 
      - "${DOCKERDIR}/mediaserver/sonarr:/config"
      - "${USERDIR}/data:/data"
      - "/etc/localtime:/etc/localtime:ro"
      - "${DOCKERDIR}/mediaserver/shared:/shared"
  firefox:
    image: lscr.io/linuxserver/firefox
    container_name: firefox
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERDIR}/mediaserver/firefox:/config
    shm_size: "1gb"
    depends_on: 
      - gluetun
    network_mode: "service:gluetun"
    restart: unless-stopped
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - ${DOCKERDIR}/mediaserver/komga:/config
      - ${USERDIR}/data/comics:/data
    ports:
      - ${KOMGA_PORT}:8080
    user: "${PUID}:${PGID}"
    # remove the whole environment section if you don't need it
    restart: unless-stopped    
  xteve: 
    container_name: xteveGuide2Go
    depends_on: 
      - gluetun
    network_mode: "service:gluetun"
    restart: unless-stopped
    environment: 
      # - "PUID=${PUID}"
      # - "PGID=${PGID}"
      - "TZ=${TZ}"
    image: "dnsforge/xteve:latest"
    volumes: 
      - "${DOCKERDIR}/mediaserver/dnsForgeXteve:/home/xteve/conf"
      - "${DOCKERDIR}/mediaserver/guide2go:/home/xteve/guide2go/conf"
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - lidarr:/config
      - "${USERDIR}/data:/data"
      #- "${USERDIR}/data/media/music:/music #optional
      #- /path/to/downloads:/downloads #optional
    ports:
      - ${LIDARR_PORT}:8686
    restart: unless-stopped
volumes:
  lidarr:
